- hosts: localhost
  remote_user: root
  tasks:
  - name: Create security group
    ec2_group:
        name: ec2-slfinal
        description: ec2-slfinal security group
        region: us-east-1
        aws_access_key: ASIA6J33NNV6HK6O4FAU
        aws_secret_key: aX7bIZIRwmganHSK0f7J+SjbwdQpB3gjXCQXDXC9
        security_token: FwoGZXIvYXdzELz//////////wEaDICo46vN2rIbZH08jCK0ARHSbb9uywyDtwzZSS7OlmbHyuYnSa4fCpJ55/DXpPt9XCBbmWOGIM4cbgKWRVIDuHhLrfBpGhVCVGwi8fZEFv4ME8tlNoZntZ+Mk54fLBEYj7dI0YsPRIT18QpV4Il/VoFd/tWq5RiDNar40JVe8sK2keyPhIzmbeSMCMtndBGBZ+sbkpn4CHUozWRRz5wRPQJjo+BuIcvN0hrK4q/q0sXw1jWHgGMuyc2adlJRJQT42c//pCjugO6NBjItL48d02jPWytKgQCt1jwL/MjU1BDwZ8KavJmFwHD4zgxCrolfA08Dv4XvxFgZ
        rules:
          - proto: tcp  # ssh
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp  # http
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp  # https
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
    register: firewall_sg


  - name: Create a new EC2 key
    ec2_key:
      name: ec2-slfinal-key
      region: us-east-1
      key_material: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"        
      aws_access_key: ASIA6J33NNV6HK6O4FAU
      aws_secret_key: aX7bIZIRwmganHSK0f7J+SjbwdQpB3gjXCQXDXC9
      security_token: FwoGZXIvYXdzELz//////////wEaDICo46vN2rIbZH08jCK0ARHSbb9uywyDtwzZSS7OlmbHyuYnSa4fCpJ55/DXpPt9XCBbmWOGIM4cbgKWRVIDuHhLrfBpGhVCVGwi8fZEFv4ME8tlNoZntZ+Mk54fLBEYj7dI0YsPRIT18QpV4Il/VoFd/tWq5RiDNar40JVe8sK2keyPhIzmbeSMCMtndBGBZ+sbkpn4CHUozWRRz5wRPQJjo+BuIcvN0hrK4q/q0sXw1jWHgGMuyc2adlJRJQT42c//pCjugO6NBjItL48d02jPWytKgQCt1jwL/MjU1BDwZ8KavJmFwHD4zgxCrolfA08Dv4XvxFgZ
      

  - name: Create an EC2 instance
    ec2:
      aws_access_key: ASIA6J33NNV6HK6O4FAU
      aws_secret_key: aX7bIZIRwmganHSK0f7J+SjbwdQpB3gjXCQXDXC9
      security_token: FwoGZXIvYXdzELz//////////wEaDICo46vN2rIbZH08jCK0ARHSbb9uywyDtwzZSS7OlmbHyuYnSa4fCpJ55/DXpPt9XCBbmWOGIM4cbgKWRVIDuHhLrfBpGhVCVGwi8fZEFv4ME8tlNoZntZ+Mk54fLBEYj7dI0YsPRIT18QpV4Il/VoFd/tWq5RiDNar40JVe8sK2keyPhIzmbeSMCMtndBGBZ+sbkpn4CHUozWRRz5wRPQJjo+BuIcvN0hrK4q/q0sXw1jWHgGMuyc2adlJRJQT42c//pCjugO6NBjItL48d02jPWytKgQCt1jwL/MjU1BDwZ8KavJmFwHD4zgxCrolfA08Dv4XvxFgZ
       
      key_name: ec2-slfinal-key
      region: us-east-1
      group_id: "{{ firewall_sg.group_id }}"
      instance_type: t2.micro
      image: ami-0813288835c686b96
      wait: yes
      instance_tags:
          Name: ec2-slfinal-key
      count_tag: Name
      exact_count: 1
      vpc_subnet_id: subnet-0ae8268246e07503a 
      assign_public_ip: yes
    register: ec2 
